### PR TITLE
Fix trainer args in simclr and swav

### PR DESCRIPTION
**Pull request by ananyahjha93**
## What does this PR do?

Restores simclr/swav back to working version. Current 0.3.0 breaks mixed precision training and single GPU training in swav.

## Before submitting
- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [ ] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests? [not needed for typos/docs]
- [ ] Did you verify new and existing tests pass locally with your changes?
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/master/CHANGELOG.md)?

## PR review
 - [ ] Is this pull request ready for review? (if not, please submit in draft mode)

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Review by Borda — CHANGES_REQUESTED** [review]
need to fix code/tests

**Comment by Borda** [comment]
@akihironitta mind chek this PR and the failing tests? :]

**Comment by akihironitta** [comment]
Sure :)

**Comment by akihironitta** [comment]
I assume they were working fine at 41bd36cc5e02a03753776078c3fcfd6226adf78b, so I just rolled back the models and tests to the commit.

**Comment by akihironitta** [comment]
This PR includes the change in https://github.com/PyTorchLightning/pytorch-lightning-bolts/pull/549.

**Review by akihironitta — APPROVED** [review]
@ananyahjha93 @Borda Should be ready to merge now. Could you have a look?

**Review by Borda — APPROVED** [review]
the SSL would need some more cleaning :D

**Comment by Borda** [comment]
@akihironitta probably just ignore this one:
```
pl_bolts/datamodules/async_dataloader.py:95: error: Cannot determine type of
'worker'  [has-type]
    ... if_worker = (not hasattr(self, 'worker') or not self.worker.is_alive(...
```

**Comment by akihironitta** [comment]
> @akihironitta probably just ignore this one:

That change is included in #542, but I can include it here, too.

**Comment by akihironitta** [comment]
> the SSL would need some more cleaning :D

I agree.

**Pull request merged**
