### PR TITLE
Raise ModuleNotFoundError when unavailable

### LINKED ISSUE #265: NameError: name 'shuffle' is not defined
### To Reproduce

Use `ImagenetDataModule` without having `scikit-learn` installed.

Inside `imagenet_dataset.py` there is the following try-except in the imports:
```
try:
    from sklearn.utils import shuffle
except ImportError:
    warn('You want to use `sklearn` which is not installed yet,'  # pragma: no-cover
         ' install it with `pip install sklearn`.')
```
so the program flow continues although sklearn might not be available.

However, the `shuffle` is used in the `UnlabeledImagenet` constructor. So in case sklearn is actually missing, it will crash with the following trace:

```
  File "/home/andrea.palazzi/.local/lib/python3.7/site-packages/pytorch_lightning/accelerators/base_accelerator.py", line 50, in train_or_test
    results = self.trainer.train()
  File "/home/andrea.palazzi/.local/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 476, in train
    self.run_sanity_check(self.get_model())
  File "/home/andrea.palazzi/.local/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 656, in run_sanity_check
    self.reset_val_dataloader(ref_model)
  File "/home/andrea.palazzi/.local/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 316, in reset_val_dataloader
    self.num_val_batches, self.val_dataloaders = self._reset_eval_dataloader(model, 'val')
  File "/home/andrea.palazzi/.local/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 236, in _reset_eval_dataloader
    dataloaders = self.request_dataloader(getattr(model, loader_name))
  File "/home/andrea.palazzi/.local/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 339, in request_dataloader
    dataloader = dataloader_fx()
  File "/home/andrea.palazzi/.local/lib/python3.7/site-packages/pl_bolts/datamodules/imagenet_datamodule.py", line 159, in val_dataloader
    transform=transforms)
  File "/home/andrea.palazzi/.local/lib/python3.7/site-packages/pl_bolts/datamodules/imagenet_dataset.py", line 74, in __init__
    self.imgs = shuffle(self.imgs, random_state=1234)
NameError: name 'shuffle' is not defined

```

### Expected behavior

I would expect `scikit-learn` to be installed automatically when installing bolts, as it's not really optional. 

Or at least, the program could fail at import time, it would still be easier to understand where the error comes from. The current way it's not obvious, because the warning gets mixed up among other info/warnings I might have on console and I found myself wondering why `shuffle` is not defined.

### Environment
- torch-related: 
  - pytorch-lightning==0.10.0
  - pytorch-lightning-bolts==0.2.2
  - torch==1.6.0+cu101
  - torchvision==0.7.0+cu101
 - OS (e.g., Linux): Ubuntu 20.04.1 LTS
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Python version: 3.7.5
 - CUDA/cuDNN version: 101

Thanks.

### PR DESCRIPTION
**Pull request by akihironitta**
# Before submitting

- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure to update the docs?   
- [ ] Did you write any new necessary tests?  

## What does this PR do?
Fixes #265.

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by Borda** [comment]
@akihironitta could you please explore @awaelchli recommendation about importing without try/catch

**Comment by akihironitta** [comment]
@Borda Thanks for reviewing as always! 
As for optional imports, https://github.com/PyTorchLightning/pytorch-lightning/issues/2266#issuecomment-671021687 suggests:
```python
if importlib.util.find_spec("some_package") is not None:
    from some_package import my_function
```
and after that, https://github.com/PyTorchLightning/pytorch-lightning/pull/2877 tried implementing `pytorch_lightning.utilities.is_some_package_available()`, but it's closed without getting merged.

Is there a preferred way of importing optional packages without try/catch? Should I wait for https://github.com/PyTorchLightning/pytorch-lightning/pull/2877 to get merged or directly use https://github.com/PyTorchLightning/pytorch-lightning/issues/2266#issuecomment-671021687?

**Comment by awaelchli** [comment]
@akihironitta 
You could do this:

```python
SKLEARN_AVAILABLE = importlib.util.find_spec("some_package") is not None
```

and then wherever you need it:
```python
if SKLEARN_AVAILABLE:
    # import something, warn or raise
```

This is my recommendation when you need a variable telling you if the package is available without the need to actually import it. 
You can also use `ModuleNotFoundError`, nothing wrong with that, but when a variable like `IS_MODULE_AVAILABLE` is required anyway, I think using importlib is cleaner. 

Hope this helps.

**Comment by akihironitta** [comment]
@awaelchli Thank you for the suggestion! I'll start using `importlib` here.

**Review by Borda — APPROVED** [review]

**Pull request merged**
