### PR TITLE
WIP: Efficient Detection Net

### PR DESCRIPTION
**Pull request by iqDF**
# Before submitting

- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to update the docs?   
- [ ] Did you write any new necessary tests?  

## What does this PR do?
Implement #1: https://github.com/PyTorchLightning/pytorch-lightning-bolts/issues/1

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by iqDF** [comment]
@pep8speaks Will fix Pep8 linting in the next commit.

**Comment by williamFalcon** [comment]
@iqDF fixed the conflicts!
this is super cool. let's get this merged

**Comment by williamFalcon** [comment]
@iqDF don't worry about builds or any of that right now. let's just get the model working (confirmed). we can work out the build issues later

**Comment by iqDF** [comment]
@williamFalcon  ok cool. will continue the work.

**Comment by williamFalcon** [comment]
@iqDF ok, we now merged a lot of the building blocks and structures.
Take a look at some of the self-supervised examples for the standard conventions :) 

looking forward to adding!

**Comment by williamFalcon** [comment]
@iqDF we finally got the v1 of bolts ready with tests and docs. Let's continue this implementation?
I noticed there is a timm dependency? mind implementing these things directly since we want to keep bolts lightweight?

**Pull request closed without merging**
