### PR TITLE
Tighten up mypy config

### PR DESCRIPTION
**Pull request by akihironitta**
## What does this PR do?
This PR updates mypy config as applied to PL in https://github.com/PyTorchLightning/pytorch-lightning/pull/5237.

Specifically, this PR adds the following mypy options.
- warn_redundant_casts = True
- warn_unused_configs = True
- ~warn_unused_ignores = True~ <- Skipped this addition. See https://github.com/PyTorchLightning/pytorch-lightning-bolts/pull/505#issuecomment-757515135

## Before submitting
- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests? [not needed for typos/docs]
- [ ] Did you verify new and existing tests pass locally with your changes?
- [x] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/master/CHANGELOG.md)?

## PR review
 - [ ] Is this pull request ready for review? (if not, please submit in draft mode)

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Review by Borda — APPROVED** [review]
is it ready to go?

**Comment by akihironitta** [comment]
It seems some of the lines with `type: ignore` (added in #444) are causing mypy errors due to `unused 'type: ignore'
comment`.
@ydcjeff Do you have any idea why this happens? `type: ignore` are used, right?

**Comment by ydcjeff** [comment]
Removing those `type: ignore` which cause errors pass in the CI (fresh start). but fail locally (cache/no cache).

**Comment by akihironitta** [comment]
@ydcjeff Right, removing `type: ignore` will fix the mypy errors on GitHub Actions, but locally, it will produce errors on the same lines... I made sure to match the installed version, but somehow mypy behaves differently between on GitHub Actions and local env.

**Comment by akihironitta** [comment]
Since we have an issue https://github.com/PyTorchLightning/pytorch-lightning-bolts/pull/505#issuecomment-757515135 with `warn_unused_ignores = True` for an unknown reason, so I'll just remove the option for now.

**Review by Borda — APPROVED** [review]

**Pull request merged**
