### PR TITLE
[WIP] Add tests for datamodules

### PR DESCRIPTION
**Pull request by akihironitta**
## What does this PR do?
Adds tests for `pl_bolts/datamodules/`.

## Before submitting
- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [ ] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure your PR does only one thing, instead of bundling different changes together? Otherwise, we ask you to create a separate PR for every change.
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?
- [ ] Did you verify new and existing tests pass locally with your changes?
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/master/CHANGELOG.md)?

## PR review
 - [ ] Is this pull request ready for review? (if not, please submit in draft mode)

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by akihironitta** [comment]
Is there any certain reason for not having tests for `pl_bolts/datamodules/*`? If so, I'll just close this PR without doing anything. https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/e6b10875d59a39a4dcf382d3a599528a40ba088c/tests/datamodules/test_datamodules.py#L1-L8

**Comment by Borda** [comment]
@akihironitta it seems to be empty, what is it about?

**Comment by akihironitta** [comment]
I'll add tests for datamodules here. Currently,

 we only have tests for

**Comment by akihironitta** [comment]
I'll add tests for datamodules here. Currently, we have tests only for `CityscapesDataModule` which was recently added.

**Pull request closed without merging**
