### PR TITLE
Update isort config and apply to the codebase

### LINKED ISSUE #422: Improve import formatting configuration
## 🚀 Feature
Although we have recently introduced isort to check import formatting in #324, I find the import order somewhat confusing, so I'd like to suggest to add the following two options to isort config. (I'm sorry I didn't explore isort config well enough in #324...)

### `force_sort_within_sections = 'True'`
```python
# before
import torch
from pytorch_lightning import Callback
from torch.nn import functional as F

# after
from pytorch_lightning import Callback
import torch
from torch.nn import functional as F
```

### `order_by_type = 'False'`
```python
# before
from torch import Tensor, nn

# after
from torch import nn, Tensor
```

We can apply this to submodules step by step like we do in PL. Let me know your thoughts on this.

### PR DESCRIPTION
**Pull request by akihironitta**
## What does this PR do?
Closes #422.

As discussed in https://github.com/PyTorchLightning/pytorch-lightning/issues/4960 and applied in https://github.com/PyTorchLightning/pytorch-lightning/pull/5142, this PR in Bolts updates the config and applies it to the codebase to match with PL.

## Before submitting
- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure to update the documentation with your changes?
- [x] Did you write any new necessary tests? [not needed for typos/docs]
- [x] Did you verify new and existing tests pass locally with your changes?
- [x] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/master/CHANGELOG.md)?

## PR review
 - [x] Is this pull request ready for review? (if not, please submit in draft mode)

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Review by Borda — COMMENTED** [review]
I would prefer to keep `force_sort_within_sections = "False"` s it is also default option

**Comment by akihironitta** [comment]
> I would prefer to keep `force_sort_within_sections = "False"` s it is also default option

Sure, let's do in that way.

**Comment by akihironitta** [comment]
@Borda `force_sort_within_sections = "False"` has been applied, so can you have a look at the changes again?

**Review by Borda — APPROVED** [review]

**Comment by Borda** [comment]
Btw, unrelated to this PR, but all PRs now show "Unchanged files with check annotations" referring to many warnings in docs, mind have look? 🐰

**Comment by akihironitta** [comment]
@Borda Sure, I will. That's what I thought I have to do :]

**Pull request merged**
