### PR TITLE
Add the Asynchronous Dataloader

### PR DESCRIPTION
**Pull request by HenryJia**
Firstly, really sorry it's been this long. I've finally got round all my uni stuff and graduated and actually have time now.

# Before submitting

- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure to update the docs?   
- [x] Did you write any new necessary tests?  

## What does this PR do?
Add the asynchronous dataloader as discussed in

https://github.com/PyTorchLightning/pytorch-lightning/pull/1521
https://github.com/PyTorchLightning/pytorch-lightning/issues/1454
https://github.com/PyTorchLightning/pytorch-lightning/issues/1404
https://github.com/PyTorchLightning/pytorch-lightning/issues/1316

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Yes I had fun coding :)

### CODE REVIEW

**Comment by williamFalcon** [comment]
@HenryJia nice. Mind fixing the coverage?

**Comment by HenryJia** [comment]
> @HenryJia nice. Mind fixing the coverage?
@williamFalcon Not entirely sure how to do that, the test requires a GPU to run since the dataloader needs a GPU, and I don't think any of the CI tests run on GPU machines?

**Comment by williamFalcon** [comment]
@Borda can we also add a set of GPUs for bolts?

Ok, we’ll merge now and make sure to add the gpus here as well 
@edenlightning

**Comment by williamFalcon** [comment]
@HenryJia 
i noticed the docs mention this works with datamodules. However, this is meant for dataloaders no?

**Comment by Borda** [comment]
> @Borda can we also add a set of GPUs for bolts?
> Ok, we’ll merge now and make sure to add the gpus here as well

yes, we were working on it with @luiscape as the best way is having Drone auto-scaling because these tests may run much longer the for PL...

**Comment by HenryJia** [comment]
> @HenryJia
> i noticed the docs mention this works with datamodules. However, this is meant for dataloaders no?
@williamFalcon 
Yes it's for wrapping datasets and dataloaders. I meant it could be used inside a datamodule in its construction, should I edit that to make it clearer?

**Comment by williamFalcon** [comment]
yes. that’s not clear from the docs right now

**Pull request merged**
