### PR TITLE
docs & clear RL pkg

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?

Cleaning reinforce and move docs

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by djbyrne** [comment]
Does it make sense to include the "results" section from the READMES as there are no plots ?

**Comment by Borda** [comment]
@djbyrne @williamFalcon I have moved all readme content to the modules so it can be included in docs

**Comment by Borda** [comment]
> Does it make sense to include the "results" section from the READMES as there are no plots ?

it seems that the images were missing, not sure if they got lost in some past PR or were not committed at all, but it the time I started this PR there was no folder with images...
@djbyrne mind share it again? otherwise, are you fine with this change?

**Comment by djbyrne** [comment]
@Borda yes sorry I meant to ask do you guys want to store benchmark results of the models in this repo ? If so I can add the images folder

**Comment by Borda** [comment]
> @Borda yes sorry I meant to ask do you guys want to store benchmark results of the models in this repo ? If so I can add the images folder

yes, add an image folder with results/illustrations to e.g. `docs/source/_images/RL` and try the images minimal so prefer jpg format and the resolution just to be fine, e.g. 600x600

**Comment by djbyrne** [comment]
@Borda it looks like this PR and #70 are on the same branch. I should have created a new one for my changes. Would it best to just merge this in as is, then create a seperate branch and PR for the results section?

**Comment by Borda** [comment]
> @Borda it looks like this PR and #70 are on the same branch. I should have created a new one for my changes. Would it best to just merge this in as is, then create a seperate branch and PR for the results section?

I merged the other one as it is smaller and try to rebase this one... and then lets add images in separate PR?

**Comment by djbyrne** [comment]
yeah sounds good :+1:

**Comment by Borda** [comment]
> yeah sounds good

@djbyrne done, mind check it and approve if you are fine with it :]

**Pull request merged**
