### PR TITLE
CI: enable py 3.8 suspend Win

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?

try to run py3.8 and drop 3.7

## Before submitting
- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [ ] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure to update the documentation with your changes?
- [x] Did you write any new necessary tests? [not needed for typos/docs]
- [x] Did you verify new and existing tests pass locally with your changes?
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/master/CHANGELOG.md)?

## PR review
 - [x] Is this pull request ready for review? (if not, please submit in draft mode)

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by akihironitta** [comment]
Is it ok to drop the tests for Python 3.7 though we still support 3.7?

**Comment by Borda** [comment]
> Is it ok to drop the tests for Python 3.7 though we still support 3.7?

I think it is fine as the python version usually have incremental/cumulative changes so we can rely on what we support the oldest and lates, I do not think that py 3.7 won't have anything which would be missing in 3.6 or 3.8/9

Well if needed we can add it back, this is mainly on saving some time :]

**Comment by akihironitta** [comment]
@Borda Sounds good.

> I would say that reveal of failing most or Win test is worse... #526

I completely agree...

**Review by akihironitta — APPROVED** [review]

**Comment by Borda** [comment]
Also, tests on macOS take double the time compare to others...

**Pull request merged**
