### PR TITLE
fix for Tests Hanging

### LINKED ISSUE #111: Minimal Requirement Tests Hanging
## 🐛 Bug
Tests run using the minimal requirements hang and are eventually canceled by CI. When run with latest requirements, test complete in ~5 minutes

Following behavior has been observed

- resnet128 gets stuck when run with all the tests, but not when you run pytest `test_resnet.py`
- `self_supervised` hangs both as a group test and single test
- gans fails when run with minimal requirements.txt 
- `test_dev_dataset` hangs when run as a group or as a single test

### To Reproduce
run unit tests with minimal requirements

### PR DESCRIPTION
**Pull request by ananyahjha93**
# Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [ ] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to update the docs?   
- [ ] Did you write any new necessary tests?  

## What does this PR do?
related to #111

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by ananyahjha93** [comment]
@Borda a few of the tests are stochastic for some reason. They failed or timed out the previous time and completed this time. The current failed test doesn't have any log to refer to. We definitely need better tests for this codebase. The self_supervised tests are taking way too much time if you look at the log.

We can probably merge this one for now as a fix.

**Comment by Borda** [comment]
> @Borda a few of the tests are stochastic for some reason.

Then we can use setting the randomness seed, right?

> They failed or timed out the previous time and completed this time.

There was a good suggestion from @djbyrne to run `fast_dev_run`

> The current failed test doesn't have any log to refer to. We definitely need better tests for this codebase. The self_supervised tests are taking way too much time if you look at the log.

Any specific suggestions?

**Comment by ananyahjha93** [comment]
@Borda I'm sorry, but stochastic in the sense that some tests fail the first time and then run when executed again. Used the fast_dev_run this time around. Also, the test which fails, fails on the ' Upload coverage to Codecov' part and not the actual tests. 

Thinking of ways to improve the coverage and how we can make tests more robust.

**Comment by djbyrne** [comment]
hey @Borda @ananyahjha93 we may want to look at having more of a focus on unit tests as opposed to the smoke/integration tests that currently provide most of our code coverage. 

The smoke tests are good to show that nothing is crashing, but doesn't necessarily ensure that everything is working as expected. Also, they tend to take much longer and due to their 'black box' nature, is more likely to contain unknown stochastic elements as @ananyahjha93 pointed out.

This is just my two cents on the matter :)

**Comment by williamFalcon** [comment]
@djbyrne yeah agree 100%.
I think we are thinking stages of tests 
- smoke tests
- script smoke tests
- correctness tests (measure a metric or something).

But the hard part is how to do that for som many models haha without downloading a ton of datasets or running long training runs.

**Pull request merged**
