### PR TITLE
[WIP] Argparser Improvements

### PR DESCRIPTION
**Pull request by nateraw**
# Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [ ] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to update the docs?   
- [ ] Did you write any new necessary tests?  

## What does this PR do?
Fixes # (issue).

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by edenlightning** [comment]
@awaelchli

**Comment by teddykoker** [comment]
Add docs please :)

**Comment by teddykoker** [comment]
Honestly I would prefer:
```
parser.add("model", MyLightningModule)
parser.add("data", MyDataModule)
```
That way the use could always add any arbitrary object they want

**Comment by nateraw** [comment]
> Honestly I would prefer:
> 
> ```
> parser.add("model", MyLightningModule)
> parser.add("data", MyDataModule)
> ```
> 
> That way the use could always add any arbitrary object they want

+1 to this. that's what `add_object_args` was before. which do you think is better function name? `.add` or `.add_object_args`? I figured the latter sounds more like argparse, but idc.

**Comment by odedbd** [comment]
@nateraw are the arguments for the different objects added into ArgumentParser groups (using add_argument_group)? I've read the code and couldn't find add_argument_group being called.

I think it would significantly help the clarity of the command line help.

Also, regarding your question to @teddykoker I prefer using add_object_args, or perhaps even add_object_specific_args, which conforms to the norm suggested in the documentation for add_model_specific_args.

**Comment by Borda** [comment]
@nateraw is it still WIP, how is it going?

**Comment by Borda** [comment]
seems dead, right? @nateraw feel free to reopen if suitable...

**Pull request closed without merging**
