### PR TITLE
Apply isort to pl_bolts/callbacks/variational.py

### PR DESCRIPTION
**Pull request by akihironitta**
## What does this PR do?
Fixes import formatting

## Before submitting
- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together? Otherwise, we ask you to create a separate PR for every change.
- [x] Did you make sure to update the documentation with your changes?
- [x] Did you write any new necessary tests?
- [x] Did you verify new and existing tests pass locally with your changes?
- [x] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/master/CHANGELOG.md)?

## PR review
 - [x] Is this pull request ready for review? (if not, please submit in draft mode)

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by akihironitta** [comment]
> does it mean that we can drop `pl_bolts.callbacks` from the ignore list?

@Borda We actually have no ignore list for isort in Bolts.

**Comment by Borda** [comment]
> > does it mean that we can drop `pl_bolts.callbacks` from the ignore list?
> 
> @Borda We actually have no ignore list for isort in Bolts.

I see it is because we have a different check here, just checking diff on the PR, not full codebase...

**Comment by akihironitta** [comment]
> > > does it mean that we can drop `pl_bolts.callbacks` from the ignore list?
> > 
> > 
> > @Borda We actually have no ignore list for isort in Bolts.
> 
> I see it is because we have a different check here, just checking diff on the PR, not full codebase...

Do we? I remember `pre-commit` only checks modified files, but I thought we have an import formatting check on the whole codebase as configured in:
https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/13863ccf1f96cb912406c029c50f4253f4599aee/.github/workflows/code-format.yml#L27

**Comment by akihironitta** [comment]
It looks that #448 has the same change as this PR

**Review by Borda — APPROVED** [review]

**Pull request merged**
