### PR TITLE
[RFC] Add missing names to `pl_bolts/datasets/__init__.py`

### PR DESCRIPTION
**Pull request by akihironitta**
## What does this PR do?
It seems strange to me that `pl_bolts/datasets/__init__.py` has only dummy datasets. This PR adds missing items to the __init__.py to make all dataset classes (and functions) available right under `pl_bolts.datasets`.

In short, this PR enables:
```python
from pl_bolts.datasets import BinaryMNIST  # This doesn't work on the current master branch.
```
where we have to write on the master branch:
```python
from pl_bolts.datasets.mnist_dataset import BinaryMNIST
```

I'd like to merge this PR since this change can make the tests for imports in #428 easier.
If not having dataset classes in `pl_bolts/datasets/__init__.py` on purpose, please just close this PR...

## Before submitting
- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [ ] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [ ] Did you make sure to update the documentation with your changes?
- [x] Did you write any new necessary tests? [not needed for typos/docs]
- [x] Did you verify new and existing tests pass locally with your changes?
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/master/CHANGELOG.md)?

## PR review
 - [x] Is this pull request ready for review? (if not, please submit in draft mode)

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by akihironitta** [comment]
@Borda Do you find this change reasonable?

**Comment by Borda** [comment]
> @Borda Do you find this change reasonable? If so, I'll move forward by adding some changes to the docs in this PR.

not sure how this helps, would it work if you have not installed all packages needed for other datamodules?

**Comment by akihironitta** [comment]
> > @Borda Do you find this change reasonable? If so, I'll move forward by adding some changes to the docs in this PR.
> 
> not sure how this helps, would it work if you have not installed all packages needed for other datamodules?

Yes. Before #338, `ModuleNotFoundError` was raised as soon as modules cannot find optional packages, which led to importing problems in the past, but #338 replaced the `ModuleNotFoundError` with warnings, so it should work without any optional packages installed.
related diff: https://github.com/PyTorchLightning/pytorch-lightning-bolts/pull/338/files#diff-30bd8712b62d3a1204186cc19600041c03996ddd4998d1fbe567843d010c7e69

Shall I keep going then?

**Comment by akihironitta** [comment]
@Borda @ananyahjha93 Would love to hear your thoughts on this.

**Comment by Borda** [comment]
@akihironitta I have added nb of workers but not sure if it is the reason for failing the test...

**Comment by akihironitta** [comment]
@Borda I guess this is ready to go once the tests pass in CI.

**Review by Borda — APPROVED** [review]

**Pull request merged**
