### PR TITLE
CI: drop code formatters

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?

requested by @williamFalcon 

## Before submitting
- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [ ] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests? [not needed for typos/docs]
- [ ] Did you verify new and existing tests pass locally with your changes?
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/master/CHANGELOG.md)?

## PR review
 - [x] Is this pull request ready for review? (if not, please submit in draft mode)

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by akihironitta** [comment]
Will we have a different formatter like `black` (which works great with `flake8`), or no more formatters in the future?

**Comment by Borda** [comment]
> Will we have a different formatter like `black` (which works great with `flake8`), or no more formatters in the future?

good question, personally I am not happy about it, pls ask @ananyahjha93 or @tchaton

**Comment by williamFalcon** [comment]
we’ll add any formatters that can work automatically for users. but right now this is a blocker for new contributors. 

imagine coming to do a simple contribution of a few lines, and you spent the next 2 hours trying to get the build to pass because you have no idea what black, mypy, isort etc are. you walk away and don’t come back because it’s too “hard” to contribute. 

so, we lose contributors and gain a few sorted lines... not worth it

**Comment by akihironitta** [comment]
I see. That totally makes sense.

**Review by akihironitta — APPROVED** [review]

**Review by tchaton — APPROVED** [review]
LGTM ! Should we add note in PR header to explain how to do formatting if people are interested ?

**Pull request merged**
