### PR TITLE
script tests for self_supervised

### PR DESCRIPTION
**Pull request by ananyahjha93**
# Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [ ] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to update the docs?   
- [ ] Did you write any new necessary tests?  

## What does this PR do?
Fixes # (issue).

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by williamFalcon** [comment]
@Borda  @ananyahjha93 what happened to this?

**Comment by Borda** [comment]
@ananyan is adding tests which we spoke about some time ago...

**Comment by ananyahjha93** [comment]
@williamFalcon this got pushed a bit due to a few things like a few blocking factors for simclr and swav. Still on my list right after those.

**Comment by Borda** [comment]
@ananyahjha93 is it still actual? if so, mid update according to the laters master...

**Comment by Borda** [comment]
@ananyahjha93 is it still actual?

**Comment by Borda** [comment]
@ananyahjha93 is it still actual?

**Pull request closed without merging**
